version: 2.1
jobs:
  build:
    docker:
      - image: ques0942/plantuml-cli # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: ls
      - run: java -jar /build/plantuml.jar -help
