version: 2.1
jobs:
  build:
    docker:
      - image: ques0942/plantuml-cli # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: ls
      - run: java -jar /build/plantuml.jar ./**/*.puml
      - run: git config user.email "ques0942@gmail.com"
      - run: git config user.name "ques0942"
      - run: git add -A
      - run: git commit -m "[ci skip] build plantuml"
      - run: git push origin ${CIRCLE_BRANCH}
  test_when:
      docker:
        - image: circleci/golang:1.13
      parameters:
        key:
          type: string
          default: ""
      steps:
        - run: echo <<parameters.key>>
        - run: <<parameters.key>> = "test"
        - run: echo <<parameters.key>>

workflows:
  workflow1:
    jobs:
      - build
  workflow2:
    jobs:
      - test_when
